// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ExampleCard: typeof import('./src/components/ExampleCard.vue')['default']
    SFAlert: typeof import('sellers-funding-design-system-vite')['SFAlert']
    SFBreadcrumbV2: typeof import('sellers-funding-design-system-vite')['SFBreadcrumbV2']
    SFButton: typeof import('sellers-funding-design-system-vite')['SFButton']
    SFCard: typeof import('sellers-funding-design-system-vite')['SFCard']
    SFCarousel: typeof import('sellers-funding-design-system-vite')['SFCarousel']
    SFFooterV2: typeof import('sellers-funding-design-system-vite')['SFFooterV2']
    SFForm: typeof import('sellers-funding-design-system-vite')['SFForm']
    SFIcon: typeof import('sellers-funding-design-system-vite')['SFIcon']
    SFInputField: typeof import('sellers-funding-design-system-vite')['SFInputField']
    SFLoader: typeof import('sellers-funding-design-system-vite')['SFLoader']
    SFMaterialButton: typeof import('sellers-funding-design-system-vite')['SFMaterialButton']
    SFMaterialInput: typeof import('sellers-funding-design-system-vite')['SFMaterialInput']
    SFPlugins: typeof import('sellers-funding-design-system-vite')['SFPlugins']
    SFTransition: typeof import('sellers-funding-design-system-vite')['SFTransition']
  }
}

export { }
